development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:f963a2af7ca63412cbeee60244a0c439@pike.redistogo.com:11958/
  channel_prefix: elearning_production
